import { card } from '../models/card';

export const contents: card[] = [
  {
    id: 1,
    thumbnail: 'https://img.youtube.com/vi/j_MuZmJNirw/maxresdefault.jpg',
    channelName: 'Netflix',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu8ez2zjv7E2Sp0qzjYCnrpBMLMm5c26MJkGBIQHww=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 25638635,
    title: 'Wednesday Addams | Season 2 Announcement | Netflix',
    embed: 'https://www.youtube.com/embed/j_MuZmJNirw',
    gif: '../../assets/img/vid1.webp',
    safeEmbed: '',
    likeCount: 595738,
    views: 14012920,
    date: new Date(2023, 0, 12),
    duration: '0:56',
    description:
      "About Netflix: Netflix is the world's leading streaming entertainment service with 223 million paid memberships in over 190 countries enjoying TV series, documentaries, feature films and mobile games across a wide variety of genres and languages. Members can play, pause and resume watching as much as they want, anytime, anywhere, and can change their plans at any time.",
    keywords: ['wednesday', 'addams', 'movie', 'serial'],
    categories: ['trending'],
  },
  {
    id: 2,
    thumbnail: 'https://img.youtube.com/vi/xF554Tlzo-c/maxresdefault.jpg',
    channelName: 'Power Couple',
    channelProfile:
      'https://yt3.googleusercontent.com/h_5EX_GD2dB4Ti3cQbQ1BjGkm_M-EN_z_mWSw7KG-kYzswbULF5bTogzGRm-KcawIqiXgcnJiOM=s176-c-k-c0x00ffffff-no-rj',
    channelSubCount: 245898,
    title: 'I solved 541 Leetcode problems. But you need only 150.',
    embed: 'https://www.youtube.com/embed/xF554Tlzo-c',
    gif: '../../assets/img/vid2.webp',
    safeEmbed: '',
    likeCount: 39422,
    views: 1009050,
    date: new Date(2022, 11, 8),
    duration: '7:43',
    description:
      "DISCLAIMER: All opinions shared on this channel are our own and don't express views or opinions of our employers. We only use our experiences and public knowledge to make our content. NO CONFIDENTIAL INFORMATION of our employers is used or shared on this channel. This is not a Professional Coaching channel, it only highlights the public resources that have worked for our careers.",
    keywords: ['coding', 'problems'],
    categories: ['learning'],
  },
  {
    id: 3,
    thumbnail: 'https://img.youtube.com/vi/CL-f66Ks_yA/maxresdefault.jpg',
    channelName: 'Gej Yu Ve?',
    channelProfile:
      'https://yt3.ggpht.com/oYmh_vAg_RMbv3BQWPhobyD8S0UOwP5W0ZUJl30Hh911AKRDKe5JTxJC8FS1fuUvmRgObuyaaA=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 87796,
    title: 'Нүцгэн нүдээр Астрономи...',
    embed: 'https://www.youtube.com/embed/CL-f66Ks_yA',
    gif: '../../assets/img/vid3.webp',
    safeEmbed: '',
    likeCount: 1520,
    views: 104411,
    date: new Date(2021, 10, 25),
    duration: '15:32',
    description:
      'Тэнгэрийг судлахад заавал телескопны шаардлага байхгүй. Эхний ээлжинд одон орны энгийн объектуудыг таних, ялгахыг биеэ даан сурч болно. Таньд хэрэгтэй зүйл гэвэл ердөө л гэрлийн бохирдол багатай цэлмэг тэнгэр бас багахан хэмжээний мэдлэг. Энэхүү бичлэгээр бүгдээрээ хэрхэн нүцгэн нүдээрээ одон оронч болохыг сурцгаая!',
    keywords: ['astronomy', 'science'],
    categories: ['learning'],
  },
  {
    id: 4,
    thumbnail: 'https://img.youtube.com/vi/JkBwd-k82IE/mqdefault.jpg',
    channelName: '에익쿠',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu9Y3Du2zy4Vg6laGb_3-eWKECdEUDneuwqpqs5-fA=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 306189,
    title: 'MBTI in Senior Center',
    embed: 'https://www.youtube.com/embed/JkBwd-k82IE',
    gif: '../../assets/img/vid4.webp',
    safeEmbed: '',
    likeCount: 2797,
    views: 55891,
    date: new Date(2022, 11, 31),
    duration: '3:31',
    description:
      '22년도 재밌었습니다~<br>▶  insta : eicku_16<br>※ 비하발언, 욕설 댓글 등 보기불편한 댓글은 삭제될 수 있습니다. 22년도 재밌었습니다~<br>▶  insta : eicku_16<br>※ 비하발언, 욕설 댓글 등 보기불편한 댓글은 삭제될 수 있습니다. 22년도 재밌었습니다~<br>▶  insta : eicku_16<br>※ 비하발언, 욕설 댓글 등 보기불편한 댓글은 삭제될 수 있습니다.',
    keywords: ['mbti', 'korean', 'animation'],
    categories: ['trending'],
  },
  {
    id: 5,
    thumbnail: 'https://img.youtube.com/vi/0DOMlNJ9sOk/maxresdefault.jpg',
    channelName: 'The New Travel',
    channelProfile:
      'https://yt3.ggpht.com/n9ZfVxi2_kdet0XKTyQX79l_w2ISOMVEU3sOEWV1DMRyOef4AsYoq2bE12HYnUlFteqrw8OzXQ=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 211893,
    title: 'London, how many languages do you speak?',
    embed: 'https://www.youtube.com/embed/0DOMlNJ9sOk',
    safeEmbed: '',
    gif: '../../assets/img/vid5.webp',
    likeCount: 35988,
    views: 1542819,
    date: new Date(2022, 11, 25),
    duration: '10:17',
    description:
      'Today we visit London, England and ask strangers how many languages they speak. Support my channel: 👉 https://www.patreon.com/thenewtravel. Support my channel: https://www.patreon.com/thenewtravel',
    keywords: ['language', 'london', 'travel'],
    categories: ['learning'],
  },
  {
    id: 6,
    thumbnail: 'https://img.youtube.com/vi/qCcnF5Jk4ZE/maxresdefault.jpg',
    channelName: 'Benj Haisch',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu9UAfBSjgPJhlW-L-4rMnYh5r9DBEKMlMAzRkkm81o=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 49289,
    title: 'The $50 Film Camera You Should Actually Buy.',
    embed: 'https://www.youtube.com/embed/qCcnF5Jk4ZE',
    safeEmbed: '',
    gif: '../../assets/img/vid6.webp',
    likeCount: 18897,
    views: 546429,
    date: new Date(2023, 0, 17),
    duration: '11:04',
    description:
      'DISCLAIMER: This video and description contain affiliate links, which means that if you click on one of the product links, I’ll receive a small commission. This helps to support the channel and allows me to continue to make videos like this.',
    keywords: ['camera', 'hobby'],
    categories: ['trending'],
  },
  {
    id: 7,
    thumbnail: 'https://img.youtube.com/vi/bXcLbGs9rlM/mqdefault.jpg',
    channelName: 'F:Eight',
    channelProfile:
      'https://yt3.ggpht.com/y0_55vKIPAKpWYOUUeLSLKCULCKLJloGbd_g0FYJIF--GZkgOFY4VLHlJGHmCmZX31wGBgDwDg=s88-c-k-c0x00ffffff-no-nd-rj',
    channelSubCount: 513,
    title: 'Ditto // Slowed to Perfection',
    embed: 'https://www.youtube.com/embed/bXcLbGs9rlM',
    safeEmbed: '',
    gif: '../../assets/img/vid7.webp',
    likeCount: 8880,
    views: 100192,
    date: new Date(2022, 5, 1),
    duration: '3:43',
    description:
      'NewJeans (뉴진스) "Ditto" // Slowed & Reverb. "Ditto" is a song recorded by South Korean girl group NewJeans for their first single album OMG. The single album was released by ADOR, a subsidiary of Hybe Corporation, on January 2, 2023, "Ditto" was released as a pre-release track on December 19, 2022.',
    keywords: ['kpop', 'newjeans', 'ditto', 'korean', 'music'],
    categories: ['music'],
  },
  {
    id: 8,
    thumbnail: 'https://img.youtube.com/vi/3ARVIkbbf3o/maxresdefault.jpg',
    channelName: 'Zach Star',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu_ix5z4zrFoi9h0bWrH1ZpOvC8jOYLyOxnO42NUBQ=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 1137000,
    title: 'Random things that will (likely) surprise you',
    embed: 'https://www.youtube.com/embed/3ARVIkbbf3o',
    safeEmbed: '',
    gif: '../../assets/img/vid8.webp',
    likeCount: 71820,
    views: 1823555,
    date: new Date(2015, 3, 15),
    duration: '11:51',
    description:
      'Get free access to over 2500 documentaries on CuriosityStream: http://go.thoughtleaders.io/112862019... STEMerch Store: https://stemerch.com/Support the Channel: https://www.patreon.com/zachstarPayPal(one time donation): https://www.paypal.me/ZachStarYT',
    keywords: ['surprise', 'random', 'hobby'],
    categories: ['learning'],
  },
  {
    id: 9,
    thumbnail: 'https://img.youtube.com/vi/oAeMP_tPmJ0/maxresdefault.jpg',
    channelName: 'Vivian',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu_r50B7TtryQ7oNvuSaNeyWRRK6b30tQLyTr9OU=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 10837,
    title: 'The Sims 4: ALL DEATHS! - Guide (2021)',
    embed: 'https://www.youtube.com/embed/oAeMP_tPmJ0',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/an_webp/oAeMP_tPmJ0/mqdefault_6s.webp?du=3000&sqp=CJetoJ4G&rs=AOn4CLBHTEAshfp6mth-nAWzm_Klwnnd2w',
    likeCount: 52839,
    views: 1940703,
    date: new Date(2021, 7, 10),
    duration: '28:00',
    description:
      "A fleshed out and straightforward step-by-step guide on how to get every death in The Sims 4 in 2021! I will teach you the easiest ways to achieve every death type in The Sims 4, up to Cottage Living Expansion Pack. If you enjoy torturing your sims as much as I do, this is the video for you! 😂 \n \n If you think that I missed something important, please tell me in the comments, and if you have any questions, please leave them down below as well, and I'll try to help you to the best of my ability. I hope you enjoyed the video! Thank you so much for watching! :)",
    keywords: ['sims', 'deaths', 'gaming', 'animation'],
    categories: ['gaming'],
  },
  {
    id: 10,
    thumbnail: 'https://img.youtube.com/vi/IUXNiDJJ_9s/maxresdefault.jpg',
    channelName: 'The Timer',
    channelProfile:
      'https://yt3.ggpht.com/x5CwBhFPLrWAaRinjnw8VAbesWtL3hO_NSpea4E5uuK9NhVo8Ln8MznY7jXuvq9fifNrlArE=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 46789,
    title: 'Pomodoro Technique 4 x 25 min - Study Timer 2 h',
    embed: 'https://www.youtube.com/embed/IUXNiDJJ_9s',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/vi/IUXNiDJJ_9s/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB7aFhV11p_arVfFtLe-vhHyHJv9A',
    likeCount: 67390,
    views: 6162108,
    date: new Date(2020, 2, 16),
    duration: '1:59:59',
    description:
      'Effective Learning Technique \n Introduction: \n The timer is divided into two parts. the first one is 25 minutes long. Here you have to work, after that you will get a 5 minutes break. This technique will help you to study more effective. *📦So that your Amazon package is always delivered quickly and you can also switch off while studying with PrimeVideo🍿 (Amazon Affiliate Link for Students):  https://amzn.to/3D1p43e',
    keywords: ['timer', 'pomodoro', 'study', 'learning', 'focus'],
    categories: ['learning', 'trending', 'live'],
  },
  {
    id: 11,
    thumbnail: 'https://img.youtube.com/vi/TURbeWK2wwg/mqdefault.jpg',
    channelName: 'Lofi Girl',
    channelProfile:
      'https://yt3.ggpht.com/KNYElmLFGAOSZoBmxYGKKXhGHrT2e7Hmz3WsBerbam5uaDXFADAmT7htj3OcC-uK1O88lC9fQg=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 11923004,
    title: '4 A.M Study Session 📚 - [lofi hip hop/chill beats]',
    embed: 'https://www.youtube.com/embed/TURbeWK2wwg',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/vi/TURbeWK2wwg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCmH2VendSeZ1r28QbHsCpmcAw3AQ',
    likeCount: 209328,
    views: 11784112,
    date: new Date(2021, 3, 27),
    duration: '1:01:45',
    description:
      'It’s that time of the night again, when everyone is asleep, except for a selected few who are still studying, vibing, and thinking about life. “4 A.M Study Session” is a beautiful collection of soft beats by a multitude of talented artists from around the world. It’s getting late so best to grab a pair of your favourite headphones - and let the relaxing sounds of lofi slowly take over 💤',
    keywords: [
      'night',
      'study',
      'chill',
      'lofi',
      'hip hop',
      'learning',
      'music',
    ],
    categories: ['learning', 'live', 'music'],
  },
  {
    id: 12,
    thumbnail: 'https://img.youtube.com/vi/A3FZze1pYoI/maxresdefault.jpg',
    channelName: 'ABC News',
    channelProfile:
      'https://yt3.ggpht.com/OOT0eq8LoW8V3PMURGYuk0kRSgRGP7EsuGZoODhHBcg1jCB1qkuIAxS-XGnjKX9Q6rf-WKTvkQ=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 14920488,
    title: 'At least 16 killed in deadly helicopter crash near Kyiv l GMA',
    embed: 'https://www.youtube.com/embed/A3FZze1pYoI',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/an_webp/A3FZze1pYoI/mqdefault_6s.webp?du=3000&sqp=CN7HoJ4G&rs=AOn4CLAAM2BzConq1jpUbq1pIc5eX08x6Q',
    likeCount: 252,
    views: 40089,
    date: new Date(2023, 0, 18),
    duration: '2:46',
    description:
      'Ukrainian officials were killed on Wednesday morning in a helicopter crash in Brovary, a town on the outskirts of Kyiv. \n WATCH FULL EPISODES OF GMA: https://abc.go.com/shows/good-morning... \n Training terrorists in your country to attack your opponents is always a bad idea. That destruction looks worse than just a helicopter crash. It looks like a NATO styled terrorist attack.',
    keywords: ['abcnews', 'ukraine', 'brovary', 'crash', 'kyiv', 'news'],
    categories: ['news'],
  },
  {
    id: 13,
    thumbnail: 'https://img.youtube.com/vi/SqRY66yfx1Q/maxresdefault.jpg',
    channelName: 'NBC News',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu-I9lAd0RgaI5DJTcxgWyFoKluM7uPD0IuH0txFAY0=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 7372898,
    title: 'LIVE: NBC News NOW - Jan. 18',
    embed: 'https://www.youtube.com/embed/SqRY66yfx1Q',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/vi/SqRY66yfx1Q/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB71nsSlS-hMZ5PFd1ucyhvNU91oQ',
    likeCount: 682,
    views: 10232,
    date: new Date(2023, 0, 19),
    duration: '0:25',
    description:
      'NBC News Digital is a collection of innovative and powerful news brands that deliver compelling, diverse and engaging news stories. NBC News Digital features NBCNews.com, MSNBC.com, TODAY.com, Nightly News, Meet the Press, Dateline, and the existing apps and digital extensions of these respective properties.  We deliver the best in breaking news, live video coverage, original journalism and segments from your favorite NBC News Shows.',
    keywords: ['livenews', 'nbcnews', 'breakingnews', 'news'],
    categories: ['news', 'live'],
  },
  {
    id: 14,
    thumbnail: 'https://img.youtube.com/vi/gB1F9G0JXOo/maxresdefault.jpg',
    channelName: 'freeCodeCamp.org',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu9UWrGceKWaqm8AF89vuxrEt8MO3E59qOoQ785Lew=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 7071233,
    title: "Learn Unity - Beginner's Game Development Tutorial",
    embed: 'https://www.youtube.com/embed/gB1F9G0JXOo',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/an_webp/gB1F9G0JXOo/mqdefault_6s.webp?du=3000&sqp=CIqqoJ4G&rs=AOn4CLDao1yRSayXoZk8oXha3tUIkuYAew',
    likeCount: 59320,
    views: 2043625,
    date: new Date(2021, 3, 15),
    duration: '7:24:39',
    description:
      'Learn to develop games using the Unity game engine in this complete course for beginners. This course will get you up and running with Unity. Free game assets included! \n This is a heavy request from me  and I know a lot of people want this - there are A LOT of free unity beginners tutorial on the internet, you should teach unity by building 3-4 big 3d projects(on different genres) and build everything from scratch',
    keywords: ['coding', 'unity', 'game development', 'gaming', 'learning'],
    categories: ['learning', 'gaming'],
  },
  {
    id: 15,
    thumbnail: 'https://img.youtube.com/vi/iaETHB54-jw/maxresdefault.jpg',
    channelName: 'Cloudx Music',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu_B4Svb9xAci_HIee6BMU5g2_dhTEZi0KQmI8IsNw=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 2053098,
    title: 'Gaming Music 2023 🎧 Best Music Mix 🎧 EDM, Trap, Dubstep, House',
    embed: 'https://www.youtube.com/embed/iaETHB54-jw',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/vi/iaETHB54-jw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAhn94Te0GiBpJunkgE9_I1M577Ig',
    likeCount: 117,
    views: 6309,
    date: new Date(2023, 0, 17),
    duration: '1:19:33',
    description:
      'Gaming Music \n best music mix,music mix 2023,remixes of popular songs,edm remix of popular songs,edm,music 2022,music mix,music,bass boosted,car music,magic music,magic music mix,new music mix,cover,remix,remix popular song,musik,musica,magic records,gaming music,best music mix 2021,best music mix 2022',
    keywords: [
      'gaming',
      'music',
      '2023',
      'edm',
      'trap',
      'dubstep',
      'house',
      'chill',
    ],
    categories: ['gaming', 'music'],
  },
  {
    id: 16,
    thumbnail: 'https://img.youtube.com/vi/DHlkWwlujS0/maxresdefault.jpg',
    channelName: 'AshStudio7',
    channelProfile:
      'https://yt3.ggpht.com/zA28uF-z2nHl5Oq4GZ9w00J7c3lMl_G1bnPJZT9nejPyWieprYAXJnzhSNXOysvZ0wtFn5IQnVo=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 5883902,
    title: '100% Creative Sports Moments',
    embed: 'https://www.youtube.com/embed/DHlkWwlujS0',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/an_webp/DHlkWwlujS0/mqdefault_6s.webp?du=3000&sqp=CKGpoJ4G&rs=AOn4CLAJdr5Emysfk_6UBMgUrkwzP8GpDQ',
    likeCount: 49389,
    views: 11103132,
    date: new Date(2022, 1, 6),
    duration: '8:03',
    description:
      "It's amazing how we are still able to appreciate every great moment in the sport that we are not familiar with. 🔔TURN ON NOTIFICATIONS TO NEVER MISS AN UPLOAD!🔔 \n Title: 100% Creative Sports Moments \n Check out my latest music upload: \n FOLLOW ME :D ❤️",
    keywords: ['creative', 'sports', 'random', 'hobby'],
    categories: ['sports'],
  },
  {
    id: 17,
    thumbnail: 'https://img.youtube.com/vi/QZSQYrp2P8c/maxresdefault.jpg',
    channelName: 'Sky Sports Premier League',
    channelProfile:
      'https://yt3.ggpht.com/so_lrPh6XZG8QdMd5wMOFhLWAM8SfudqKoJhIe0vKUyk3LsQtNdCPvDtDtLSoTnZ4ZnrVLVm6Q=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 4208839,
    title:
      "They've been left to be embarrassed 😬 | Paul Merson shocked by Tottenham's tactics",
    embed: 'https://www.youtube.com/embed/QZSQYrp2P8c',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/an_webp/QZSQYrp2P8c/mqdefault_6s.webp?du=3000&sqp=CIqToZ4G&rs=AOn4CLCBPpEpPTAcQxieANV4TOsL6qW_bA',
    likeCount: 5812,
    views: 428282,
    date: new Date(2023, 0, 16),
    duration: '4:26',
    description:
      "SUBSCRIBE ► https://bit.ly/SubscribeSkySportsPL \n PREMIER LEAGUE HIGHLIGHTS ► http://bit.ly/SkySportsPLHighlights2223 Paul Merson believes Tottenham's midfield were left to be embarrassed by Arsenal today, with the rest of the Super Sunday panel praising the impressive Gunners. ",
    keywords: ['embarrassed', 'Paul Mersen', 'Tottenham', 'sports', 'football'],
    categories: ['news', 'sports'],
  },
  {
    id: 18,
    thumbnail: 'https://img.youtube.com/vi/tiwjvBSS_Wk/maxresdefault.jpg',
    channelName: 'Nintendo of America',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu8a6aVd0p2fKpl189AtJD2urgWHLvJUaT_N3zHTuw=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 8837483,
    title: 'Nintendo Switch Sports - Overview Trailer - Nintendo Switch',
    embed: 'https://www.youtube.com/embed/tiwjvBSS_Wk',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/an_webp/tiwjvBSS_Wk/mqdefault_6s.webp?du=3000&sqp=CJDFoJ4G&rs=AOn4CLD-TKJO9SOo27oxxLCwiosAVDBNAQ',
    likeCount: 34789,
    views: 1465556,
    date: new Date(2022, 2, 31),
    duration: '5:26',
    description:
      'Enjoy six sports with family and friends locally and online in Nintendo Switch Sports! Play Soccer, Volleyball, Bowling, Tennis, Badminton, and Chambara using intuitive motion controls with a Joy-Con controller. Face off against sports rivals near and far to earn in-game rewards, or aim for the prestigious Pro League! A seventh sport, Golf, will be added this fall.',
    keywords: ['nintendo swtich', 'nintendo', 'sports', 'gaming', 'hobby'],
    categories: ['gaming', 'sports'],
  },
  {
    id: 19,
    thumbnail: 'https://img.youtube.com/vi/O9GvZhDC9CM/maxresdefault.jpg',
    channelName: 'Vanity Fair',
    channelProfile:
      'https://yt3.ggpht.com/ytc/AMLnZu_HSbRiu_9ZABap8fa-rCJXVPMosQniX32E1UKa3NY=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 125898,
    title:
      "Louis Vuitton's Nicolas Ghesquière Breaks Down His Fashion Career | Vanity Fair",
    embed: 'https://www.youtube.com/embed/O9GvZhDC9CM',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/an_webp/O9GvZhDC9CM/mqdefault_6s.webp?du=3000&sqp=CJ7EoJ4G&rs=AOn4CLAV2m2a7a-bTgbdUR5ZpL_eCiUhMA',
    likeCount: 6890,
    views: 125382,
    date: new Date(2020, 11, 24),
    duration: '18:23',
    description:
      " Louis Vuitton's creative director Nicolas Ghesquière takes us through his career in fashion design. From assisting Jean Paul Gaultier to creative directing at Louis Vuitton, Nicolas breaks down creative directing at Balenciaga, winning a CFDA for Womenswear Designer of the Year, creating The Lariat (Balenciaga's 'It' bag), designing Jennifer Connelly's 2002 Oscar dress, and much more.",
    keywords: ['lv', 'louis vuitton', 'nicolas', 'fashion', 'design', 'brand'],
    categories: ['fashion&beauty'],
  },
  {
    id: 20,
    thumbnail: 'https://img.youtube.com/vi/vd5z6lLQzBY/mqdefault.jpg',
    channelName: 'Fashion Channel',
    channelProfile:
      'https://yt3.ggpht.com/LDjxqjRYumJFfV1zHdPpwyV_KhQIqYFI0v5w1j420zb00iTlK4psGtJCV493P_q9BDxvOudUoGY=s88-c-k-c0x00ffffff-no-rj',
    channelSubCount: 2793888,
    title: 'Vintage in Pills VIVIENNE WESTWOOD Spring 1995 - Fashion Channel',
    embed: 'https://www.youtube.com/embed/vd5z6lLQzBY',
    safeEmbed: '',
    gif: 'https://i.ytimg.com/an_webp/vd5z6lLQzBY/mqdefault_6s.webp?du=3000&sqp=CPCkoJ4G&rs=AOn4CLBRyXXiGPimd7TUESwyk4Y_B7h4eQ',
    likeCount: 712,
    views: 201665,
    date: new Date(2022, 2, 25),
    duration: '5:01',
    description:
      'Videos, fashion, stylists, models, the biggest fashion events pass by us. \n Accurate descriptions for every video since 1982 with attention to the smallest details, this is what makes fashion channel the best tool to immerse yourself in the fashion world at 360°. \n Beauty advices, news, secrets, backstage and exclusive fashion shows are all included within our channel. \n All videos are available in high resolution formats full HD on the YouTube Fashion Channel. \n Follow us and our channel if you want to keep up with new trends!',
    keywords: ['fashion', 'ss95', 'vivienne westwood', 'trend'],
    categories: ['fashion&beauty'],
  },
];
